version: "3.7"

services:
  frontend:
    image: neto002/store-frontend
    restart: always
    build:
      context: .
      dockerfile: Dockerfile
    networks:
      - demo

networks:
  demo:
    driver: bridge
